language: c
sudo: false

matrix:
  include:
  - compiler: gcc
    env: CFLAGS="-std=gnu99"
  - compiler: clang
  - dist: trusty
    env: CFLAGS="-std=gnu99"
    compiler: gcc

script:
    - make -j2 -k quiet=1
    - make -k check quiet=1
